version: '2.1'

services:

  attendance-db:
    container_name: attendance-db
    build: ./project/db
    ports:
        - 5435:5432  # expose ports - HOST:CONTAINER
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: exit 0

  attendance-api:
    container_name: attendance-api
    build: .
    volumes:
      - '.:/usr/src/app'
    ports:
      - 5000:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
      - DATABASE_URL=postgres://postgres:postgres@attendance-db:5432/attendance_dev
    depends_on:
      attendance-db:
        condition: service_healthy
    links:
      - attendance-db